#!/bin/bash

user=$(whoami)
base_path="/home/$user"


dir="$base_path/.fzf" 
printf "\nDo you want to setup FZF. (y/n): " && read -r opt
if [[ $opt =~ ^[Yy]$ ]]; then
  $dir/install
else
  printf "\t - skipping fzf setup.\n"
fi