#!/bin/bash


user=$(whoami)
base_path="/home/$user"

set -u

# Update essential packages
sudo yum update && sudo yum install -y \
    zsh \
    git \
    htop \
    shellcheck \
    curl \
    #tmux