#!/bin/env bash
echo "CMD > sudo apt update"
sudo apt update

echo;

echo "CMD > sudo apt install xfce4 xfce4-goodies"
sudo apt install xfce4 xfce4-goodies
# sudo apt install gnome-panel
# gnome-panel &

echo;

echo "CMD > sudo apt install tightvncserver"
sudo apt install tightvncserver

echo;

echo " ***** Choose no for view only password *********"
vncserver

echo;

echo "Setting up vncserver as a system service"

echo "CMD > vncserver -kill :1"
vncserver -kill :1

echo;

echo "CMD > mv ~/.vnc/xstartup ~/.vnc/xstartup.bak"
mv ~/.vnc/xstartup ~/.vnc/xstartup.bak

echo "CMD > cat ~/.vnc/xstartup"
cat << EOT >> ~/.vnc/xstartup
#!/bin/bash
xrdb $HOME/.Xresources
xsetroot -solid grey
startxfce4 &
export XKL_XMODMAP_DISABLE=1
/etc/X11/Xsession
EOT

echo;

echo "CMD > sudo chmod +x ~/.vnc/xstartup"
sudo chmod +x ~/.vnc/xstartup

# vncserver

# Running vnc as system service
echo "CMD > cat vncserver@.service"
user=$(whoami)
cat << EOT >>  template_vncserver@.service

[Unit]
Description=Start TightVNC server at startup
After=syslog.target network.target

[Service]
Type=forking
User=$user
Group=$user
WorkingDirectory=/home/$user

PIDFile=/home/$user/.vnc/%H:%i.pid
ExecStartPre=-/usr/bin/vncserver -kill :%i > /dev/null 2>&1
ExecStart=/usr/bin/vncserver -depth 24 -geometry 1600x900 :%i
ExecStop=/usr/bin/vncserver -kill :%i

[Install]
WantedBy=multi-user.target
EOT

echo;

echo;

echo "CMD > mv template_vncserver@.service /etc/systemd/system/vncserver@.service"
sudo bash -c 'mv template_vncserver@.service /etc/systemd/system/vncserver@.service'

echo;

echo "CMD > sudo systemctl daemon-reload"
sudo systemctl daemon-reload

echo;

echo "CMD > sudo systemctl enable vncserver@1.service"
sudo systemctl enable vncserver@1.service


echo;

echo "CMD > sudo systemctl start vncserver@1"
sudo systemctl start vncserver@1

echo;

echo "CMD > sudo systemctl status vncserver@1 | grep Active"
sudo systemctl status vncserver@1 | grep Active

echo;

# JetBrains Toolbox
# cd ~/Downloads
echo "CMD > wget -cO jetbrains-toolbox.tar.gz"
wget -cO jetbrains-toolbox.tar.gz "https://data.services.jetbrains.com/products/download?platform=linux&code=TBA"

echo;

echo "CMD > tar -xzf jetbrains-toolbox.tar.gz"
tar -xzf jetbrains-toolbox.tar.gz

DIR=$(find . -maxdepth 1 -type d -name jetbrains-toolbox-\* -print | head -n1)

echo;

echo "*********\n\tChoose the number corresponding to `/usr/bin/xfce4-terminal.wrapper`*************"
sudo update-alternatives --config x-terminal-emulator

echo;

echo "CMD > Run the following command on startup"
echo $DIR./jetbrains-toolbox