set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-b

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Session management

bind C-n command-prompt -p "New Session:" "new-session -A -s '%%'"
bind C-l display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind C-k display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | fzf --reverse | xargs tmux kill-session -t"
bind C-r command-prompt -p "Rename session: " "rename-session '%%'"
bind C-w command-prompt -p "Rename window: " "rename-window '%%'"
bind K confirm kill-session


# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Option+Left/Right to switch windows
bind -n M-Left  previous-window
bind -n M-Right next-window

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

set -g @catppuccin_flavour 'mocha'

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g status-position top

set -g @catppuccin_left_separator "█"
set -g @catppuccin_right_separator "█"
set -g @catppuccin_user "off"
set -g @catppuccin_host "off"

# available colors: white, gray, dark_gray, light_purple, dark_purple, cyan, green, orange, red, pink, yellow
# set -g @plugin 'dracula/tmux'
# set -g @dracula-show-powerline true
# set -g @dracula-plugins "battery kubernetes-context" 
# set -g @dracula-show-flags true
# set -g @dracula-show-left-icon session
# set -g @dracula-[plugin-name]-colors "[background] [foreground]"
# set -g @dracula-cpu-usage-colors "pink dark_gray"
# set -g @dracula-border-contrast true
# set -g @dracula-show-empty-plugins false
# set -g @dracula-battery-label "Battery"
# set -g @dracula-kubernetes-hide-user true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

