# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
#

font_family 	JetBrainsMono Nerd Font Mono
font_size 	14

bold_font        auto
italic_font      auto
bold_italic_font auto

disable_ligatures no
enable_audio_bell no

shell 			zsh
shell_integration 	disabled

cursor_shape 		block

remember_window_size	no
initial_window_width	640
initial_window_height	480

window_padding_width 	5
cursor_blink_interval	0

background_opacity	0.90

scrollbar_handle_opacity	0
scrollbar_track_opacity		0
scrollbar_track_hover_opacity	0


sync_to_monitor			no

confirm_os_window_close		0
